name: Install and test @ava/cooperate
on:
  push:
    branches:
    - main
  pull_request:
    paths-ignore:
    - '*.md'
jobs:
  nodejs:
    name: Node.js
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [^12.22, ^14.17, ^16.4, ^17]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install --no-audit
      - run: npm test
      - uses: codecov/codecov-action@v2
        with:
          file: coverage/lcov.info
          name: ${{ matrix.node-version }}
